### ISSUE TITLE
Causes Exchange ECP to fail

### ISSUE THREAD

**Issue by Tom5051** [Conflux-Chain/helios#1355]
Having this add on caused me no end of time wasting.
I use the latest Mozilla and the wallet add on is enabled. when i try to manage my microsoft exchange 2016 cluster, I get constant errors:

"Your request couldn't be completed. Please try again in a few minutes."

Why would the wallet extention from you guys be messing with security for other apps? Seems VERY DODGY to me.

Fix it immediately.

**Comment by Tom5051** [comment]
This comes up constantly. Goes away when the wallet extension is disabled or removed.
![image](https://user-images.githubusercontent.com/58039085/219677330-7c22abc6-38f0-471e-9ed0-59f56579dc38.png)

**Comment by zctocm** [comment]
@Tom5051 
So when you only use the Microsoft exchange 2016 cluster, the error will occur, and at other times, it does not happen?
Please upload the error log. It is in the tab 'Console' of your browser. 
Thanks.
