### ISSUE TITLE
Cannot disconnect a wallet from a site

### ISSUE THREAD

**Issue by miguelsalazar** [Conflux-Chain/helios#828]
Once I connect my wallet to a site, I can't disconnect it and remove the dapp connection. The "Connected sites" panel also doesn't show up on (at least) some sites where the wallet is connected to.

**Comment by zctocm** [comment]
> 

hi, what is the version of your FluentWallet? I suggest that you upgrade to Version 1.5.0.

**Comment by angelia-yuqi-personal** [comment]
Is your system Ubuntu?

**Comment by miguelsalazar** [comment]
Update to 1.5.0. Working now!
